data = [
    {
        "Id": 9833,
        "first_name": "Roy",
        "last_name": "Haag",
        "email": "roy.haag@email.com",
        "phone_number": "+94 1-714-182-2052",
        "avatar": "https://robohash.org/dictarepudiandaedoloremque.png?size=300x300",
        "address": {
            "city": "Cummeratastad",
            "street_name": "Shavonda Roads",
            "street_address": "850 William Hill",
            "zip_code": "21027-3291",
            "country": "United States",
        },
        "Orders": None,
        "LoyaltyLevel": 0,
    },
    {
        "Id": 147,
        "first_name": "Lucio",
        "last_name": "Hodkiewicz",
        "email": "lucio.hodkiewicz@email.com",
        "phone_number": "+252 1-216-516-6200 x710",
        "avatar": "https://robohash.org/debitispraesentiumlaboriosam.png?size=300x300",
        "address": {
            "city": "East Shavonnestad",
            "street_name": "Larson Summit",
            "street_address": "6238 Brandon Village",
            "zip_code": "16797",
            "country": "United States",
        },
        "Orders": None,
        "LoyaltyLevel": 2,
    },
    {
        "Id": 7576,
        "first_name": "Marlene",
        "last_name": "Renner",
        "email": "marlene.renner@email.com",
        "phone_number": "+370 598.874.3364 x52787",
        "avatar": "https://robohash.org/porrovoluptateseligendi.png?size=300x300",
        "address": {
            "city": "Lake Josueburgh",
            "street_name": "Beier Center",
            "street_address": "3380 Price Meadow",
            "zip_code": "89790",
            "country": "United States",
        },
        "Orders": None,
        "LoyaltyLevel": 0,
    },
    {
        "Id": 6890,
        "first_name": "Sonny",
        "last_name": "Boyer",
        "email": "sonny.boyer@email.com",
        "phone_number": "+233 1-671-028-6865",
        "avatar": "https://robohash.org/quiiuretempore.png?size=300x300",
        "address": {
            "city": "East Olivia",
            "street_name": "Langosh Rue",
            "street_address": "6688 Oralia Harbor",
            "zip_code": "55385-5420",
            "country": "United States",
        },
        "Orders": None,
        "LoyaltyLevel": 1,
    },
]
